### ISSUE TITLE
코드스피츠 76 CSS Rendering 2회차

### ISSUE THREAD

**Issue by qlqnf16** [qlqnf16/code-spitz-study#18]
# Modern Box
![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/58a0a875-9787-4076-aedc-82f6b9d00463)

Modern Box Model은 box-shadow, outline 을 포함

## Box Shadow

- box-shadow 의 거리를 0으로 주면 둘러싸는 상자가 돼버린다. blur 안주고 size 1로 잡으면 정확히 border와 같은 모양으로 그려짐. box-shadow를 border처럼 사용할 수 있다. 
자리는 border-box 바깥쪽. 
geometry에서 계산되지 않고, fragment에서 작동함. => 다른 상자가 밀려나거나 하지 않음
- inset 속성을 주면 border-box 안쪽에도 그릴 수 있음
- 여러겹 가능

## Outline 

- box-shadow 와 같은 위치. geometry에 영향을 끼치지 않음 
- box-shadow는 border-radius의 영향을 받음 / outline은 받지 않음 (이젠 받음!)

## box-sizing 

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/099ae384-1b4b-42c5-82a0-69cdf756e653)

CSS의 기본값은 content-box
* content-box: 내부 content의 사이즈를 보장하고 싶을 때
* border-box: element 자체의 크기를 보장하고 싶을 때

사이의 흰 공간은 inline-block 속성 때문에 생긴 거 code 내부의 공백을 인식한 것이다
요걸 없애려면? `</div><div>` 이런식으로 써주면 됨

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/cbcd3cc8-f70d-47e6-8a88-7f5f7b5df45f)

배경은 border 밑에까지 채워진다
그림을 그려주는 frament 영역은 border-box 까지

### box-shadow

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/8864ba62-c2ba-448b-b64e-f99335169e73)

geometry 영역 그린 뒤에 fragment 영역이 그려진다. 순서가 존재한다.

#### position: relative

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/b2acf164-d1ad-4a8e-a625-89b2fbb542e7)

position relative는 normal 플로우 이후에 그려진다.
Geometry 계산 -> fragment -> position relative 에 의해 geometry 재계산 => box shadow 영역을 덮는다

#### box-shadow

```css
border-radius: 50%;
box-shadow: 0 0 0 10px #aa0, 0 0 0 20px #0a0, inset 0 0 0 10px #aa0, inset 0 0 0 20px #0a0;
// 그려지는 순서는 선언의 반대쪽부터
```
![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/1531ae56-25d9-4286-b2b6-288833994496)

애니메이션도 넣을 수 있다!
```css
@keyframes ani {
    from {
        box-shadow: 0 0 0 0 #aa0, 0 0 0 0 #0a0, inset 0 0 0 0 #aa0, inset 0 0 0 0 #0a0;
        transform: rotate(0);
    }

    to {
        box-shadow: 0 0 0 10px #aa0, 0 0 0 20px #0a0, inset 0 0 0 10px #aa0, inset 0 0 0 20px #0a0;
        transform: rotate(360deg);
    }
}
```

### outline 활용법

스티치.. 근데 세월이 지나면서 이제 불가능해진
![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/8cd09f3b-d764-4a3f-a977-9f90336e0acd)
![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/42e36423-0120-4cf4-a2f9-1a011f964059)

```css
  .stitch {
      background: brown;
      border-radius: 15px;
      outline: 10px solid brown;
      border: 1px dashed #fff;
      color: #fff;
      box-shadow: 0 0 0 10px brown;
      display: block;
      margin-top: 20px;
  }
```

# Position

포지션 모델: static | relative | absolute | fixed

## caret position & offset

CSS로 작성한 추상적 명령은 geometry 계산 뒤 fixed 값을 이용한 명령이 된다
이 계산된 Fixed Number를 offset 이라고 함.  => 참고만 가능, 수정이 불가능
우리의 명령은 희망사항일 뿐 실제로 그리는 건 브라우저의 역할

frame: 브라우저는 성능을 위해 변경사항을 모아놨다가 한 번에 계산하려고 하고, 이 그리는 단위를  frame 이라고 한다.
근데 offset은 조회하는 즉시 다시 그림 => 따라서 offset을 그림그리는 로직 사이에 계속 넣으면 성능 저하가 일어난다.
=> 레이아웃이 변하는 중에 offset을 조회하는 건 조심해야 한다~

### Offset Parent

오프셋을 계산하는 가장 기본적 로직: 기준점 찾기. 그 기준점을 offset parent 라 한다.
**DOM Parent !== Offset Parent**

1. null => chrome (브라우저의 바운드 박스 기준)
   - root, html, body
   - position: fixed
   - out of dom tree

2. recursive search
  - parent.position: fixed = null
  - parent:position: !static = ok 
    - absolute의 offset parent가 될 수 있는 건 absolute 와 relative 뿐
    - relative는 주로 static 안에 absolute를 넣기 위한 컨테이너로서 사용 
  - body = ok
  - td, th, table = ok (근데 이거 브라우저에서 안됨 넣을라면 div relative 넣어줘야 함)
  - parent.parent continue (부모 위치를 찾으러 계속 재귀 진행)

### Offset Value

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/b8b42dc1-9efa-4b33-9fec-06ae86852fbd)

offsetLeft, offsetWidth, offsetScrollTop.. 이런것들이 있다
scroll이 붙은 게 진짜 content의 크기

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/75d8de80-06eb-46be-ab0c-39c7dcc5340a)

```html
<div style="width: 200px; height: 200px; background: yellow; margin: 100px;">
    <div style="width: 100px; height: 100px; position: absolute; background: red;"></div>
    <div style="width: 100px; height: 100px; position: absolute; background: blue; left: 0;"></div>
</div>
```
position absolute 의 기본값은 static 부모를 바라본다
left 값을 직접 설정한 다음에야 offset parent를 찾기 시작한다.

**left, top**
- static: 무시
- absolute: offset parent 로부터의 거리
- relative: normal flow로 그려졌을때부터의 거리
