### ISSUE TITLE
코드스피츠 76 CSS Rendering 4회차

### ISSUE THREAD

**Issue by qlqnf16** [qlqnf16/code-spitz-study#20]
# Transform 3D & scss & compass

이쯤부턴 어느정도 수학이 필요하다!

### 그래픽 파이프라인
- geometry (reflow) - reflow를 하면 전체적으로 repaint 해야 하므로 비용이 크다
- framgment (repaint)
- post process - geometry, frament 가 모두 끝난 후 한 번 더 가공. 완성된 픽셀값을 변형시킴

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/7f760483-4b0a-44b7-b316-7153205f12a8)
![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/b634f48b-94b5-4754-928e-24a4d3af287e)

#### buffer
x, y의 색을 저장한 2차원 배열 => 모던 브라우저는 이 buffer를 이용해 그림을 그림
GPU가 그림을 그리는 방법: CPU가 가공한 값을 받아서 GPU가 그리는 것. 
 - CPU를 이용해 geometry 계산, fragment 를 채우고 
 - 이 정보를 담은 buffer를 GPU에 건냄. 
 - GPU가 post process 작업을 한 뒤 최종적으로 그림을 그림

화면 처리의 부하를 CPU와 GPU가 나눌 수 있도록 하는 것이 post process의 핵심
3D는 post process

## Transform 3D

- perspective: 원근 (모니터와 나의 눈 사이의 거리. z index, 화각 등에 영향)
- perspective-origin: 바라보는 지점
  ![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/c7c077bf-ba2c-411a-b31d-2d3ea2b905f0)
- transform-style: 자식 element가 부모의 3d 속성을 이어받을 수 있도록 하는 속성
  ```
   transform-style: preserve-3d;          //DOM의 계층 구조를 post process에 넘겨줌
   transform-style: flat;
   ```
- transform-origin: 변형이 일어나는 기준, 축
- backface-visibility: 뒷면이 보이게 할 지 투명하게 할 지 구분. 기본값: visible
  - 활용법1 서로다른 두 엘레먼트의 frontface를 다른 색깔로 해놓고 뒤집어주면 앞뒷면이 다른 객체가 생김
  - 활용법2 부하조절 - 보통 뒷면을 보여줄 일이 거의 없음

이 기법은 **그림 그리는 부하를 의도적으로 분산시키기 위해서**도 사용된다
ex. rotateX: 0 은 그냥 평면인데, 이 속성값 자체가 GPU의 역할 => GPU에 부하를 미룸

## DRUM

![image](https://github.com/qlqnf16/code-spitz-study/assets/37537216/0b9d964d-8332-4b58-a510-d18bb919f576)

css sprite: 한장의 이미지를 쪼개서 쓰는 기법 => 이렇게 쪼개진 걸 Atlas라고 함
이 쪼개진 면들을 Face, 얘네를 모아서 만든 한 덩어리를 mash 라고 함

```css
margin: -${h/2}px 0 0 -${w/2}px;  // x, y의 위치를 중앙으로 보내는 것
background-position: -${tx}px ${ty}px;  // atlas의 위치를 지정
```

## SCSS & Compass

```scss
$pi: 3.141592; // 변수할당 $를 앞에, = 대신 :
@function atan2($y, $x) {   // keyword는 @붙여서 
  @if $x > 0 {
    @return atan($y/$x);    // atan 은 compass 에서 import 해온 함수
  }
  @if $x < 0 {
    @if $y >= 0 {
      @return atan($y/$x) + $pi;
    }
    @if $y < 0 {
      @return atan($y/$x) - $pi;
    }
  }
  @return atan($y/$x);
}
// scss 는 변수,함수,제어문 외에 아무것도 없음
// 나머지는 외부에서 라이브러리를 주입받아야 사용할 수 있음

@mixin face($w, $h, $x, $y, $z, $rx, $ry, $rz, $tx, $ty) {
  position: absolute;
  width: #{$w}px;     // #{} temlpate literal처럼 사용
  height: #{$h}px;
  margin-top: -#{$h/2}[x];
}

@for $i from 0 through $sides {   
  .mash>div:nth-child(#{$i}) {      // for문과 nth-child는 함께 많이 사용됨
    @include face($w,$h,...)
  }
}
```

scss를 적어놓으면 sass 컴파일러가 css를 만들어준다
브라우저의 부하를 줄이고 js의 의존도를 낮출 수 있음
