### ISSUE TITLE
코드스피츠 76 CSS Rendering 5회차

### ISSUE THREAD

**Issue by jihyuunn** [qlqnf16/code-spitz-study#21]
### Semantic Web

- HTML 태그를 화면에 보이는 요소가 아니라 의미를 가지게 태깅하자, 화면에 보이는 건 css로 조종하자
- 왜? 검색 엔진이 HTML문서를 읽어들였을 때 -> 크롤러, 데이터베이스 화하기 좋게 만들자

#### DOM

- 의미를 갖도록 태깅(쓸데없이 tag 안씀. tag 수가 매우 줄어듦)
- 화면의 구성요소로 DOM을 평가할 수 없음. 태그 순서와 DOM 순서가 다를 수 있다.

#### CSS Selector

- DOM 구조에 밀접하게 선택 (div > span > 등등 보이는 모양에 관련된 selector를 사용)
- .class 구문으로 의미를 부여하게 된다.
- 근데 class로 의미부여를 한다고 그게 시맨틱 웹이 되는건 아님

#### CSS

- 의미와는 무관한 프로퍼티(그래픽스 렌더링과 관련된 것)

->  DOM과 CSS를 연결하는게 CSS Selector, 그림을 어떻게 그려라와 실제 내용과 의미를 연결하는 것. -> CSS Selector에 따라 유지보수가 쉬워지는지, 유기적인 연결이 되는지가
결정된다.   
-> selector때문에 DOM을 함부로 못바꿈.

#### 문제

1. DOM을 스타일에 맞춰 제작
2. 태그의 변화가 스타일을 깨먹음(1번의 문제가.. div -> ul+li로 바꾸면?)  
   -> 유지보수 불가능한 HTML과 CSS  
   -> Semantic Selector 사용하자!

### CSS Attribute Selector

- 대괄호로 시작. attribute를 기반으로 element선택할 수 있게하는 속성
- `Input type=text, [type]` 이 속성을 갖고있는 애들 다 가져와
- `[type=text]` 타입 텍스트인 애 다 가져와

### Query Style Selector

- DB query selector랑 비슷
- `base selector[field conditions][..][..]`

```scss
#join {
  [name='userid'] {
    border: 1px solid #f00
  }

  [name='pw'] {
    border: 1px solid #0f0
  }

  [name='nick'] {
    border: 1px solid #00f
  }
}
```

```html

<form id="join">
    <input type="text" name="userid"/>
    <input type="password" name="pw"/>
    <input type="text" name="nick"/>
</form>
```

### HTML5 MICRODATA

- 시맨틱 스펙 정리. 이러한 속성을 이용해서 기술을 하자..?
- div를 scope로 지정하면 그 안에 태그가 모두 지정됨. 의미론적 구역이 아닌 DOM, Semantic구조 일치되는 형태.
- itemscope - 적용범위 설정(의미가 적용되는 태그의 범위)
- itemtype - 스키마 설정(스코프 안에서 타입을 설정해주고)
- itemid - 특정 id 부여 등등..

### Schema.org

- 표준화 되어있는 데이터 구조를 공유하자해서 만든 사이트
- 마이크로 데이터로 되어있는 스키마들을 공유하고 있다

```html

<body itemscope itemtype="http://schema.org/WebPage">
<h1 itemprop="name">code spitz</h1>
<p itemprop="description">desc</p>
<ul>
    <li itemscope itemtype="http://scheme.org/CollegeOrUniversity">
        <h1 itemprop="name"></h1>  <!-- 다른 scope의 name -->
        <p itemprop="description"></p>
    </li>
</ul>
</body>
```

- 쿼리 엔진같은게 와서 분석하면 완전한 데이터가 됨

```scss
[itemtype$='WebPage'] {
  [itemprop='name'] {
    font-size: 20px;
    padding: 0
  }

  [itemprop='description'] {
    font-size: 14px
  }
}

[itemtype$='CollegeOrUniversity'] {
  [itemprop='name'] {
    font-size: 15px
  }

  [itemprop='description'] {
    font-size: 12px;
    line-height: 15px;
  }
}
```

- 태그가 아예 안나옴.

### HTML Dataset

- tag에 뭔가 원하는 속성을 넣고 싶을 때 -> dataset
- W3C 정규 스펙.
- schema org가서 공부할 필요 없이 회사에서 약속한대로 사용하면 된다.
- id, class는 디자인을 위해서 비워두자.. 여기에 의미를 넣지 말자..

```html

<div data-id="123" data-member-id="abc"></div>
<!-- console.log(div.dataset.memberId) abc -->
<body data-type="http://schema.org/WebPage">
<h1 data-prop="name">code spitz</h1>
<p data-prop="description">desc</p>
<ul>
    <li data-type="http://scheme.org/CollegeOrUniversity">
        <h1 data-prop="name" data-name></h1>  <!-- 그냥 이 속성이 있는지 체크용으로만. 꼭 값을 넣지않아도 됨 -->
        <p data-prop="description"></p>
    </li>
</ul>
</body>
```

```scss
[data-type$='WebPage'] {
  [data-prop='name'] {
    font-size: 20px;
    padding: 0
  }

  [data-prop='description'] {
    font-size: 14px
  }
}

[data-type$='CollegeOrUniversity'] {
  [data-prop='name'] {
    font-size: 15px
  }

  [data-prop='description'] {
    font-size: 12px;
    line-height: 15px;
  }
}
```

- 더 간단해졌다
- 유지 보수가 쉬운 방법이 뭔지 고민해야함. 그 방법 중 하나가 시맨틱

다차원 쿼리..?

```html

<table>
    <thead>
    <th>번호</th>
    <th>이름</th>
    <th>1강</th>
    <th>2강</th>
    <th>3강</th>
    <th>개근</th>
    </thead>
    <tr data-id="1">
        <td>1</td>
        <td data-name="a">a</td>
        <td data-1="on">출석</td>
        <td data-2="on">출석</td>
        <td data-3="on">출석</td>
        <td>개근</td>
    </tr>
    <tr data-id="2">
        <td>2</td>
        <td data-name="b">b</td>
        <td data-1="on">출석</td>
        <td data-2="off">결석</td>
        <td data-3="off">결석</td>
        <td>개근</td>
    </tr>
    <tr data-id="3">
        <td>3</td>
        <td data-name="c">c</td>
        <td data-1="off">결석</td>
        <td data-2="off">결석</td>
        <td data-3="off">결석</td>
        <td>개근</td>
    </tr>
</table>

```

```scss
[data-1='on'], [data-2='on'], [data-3='on'] {
  color: green
}

[data-1='off'], [data-2='off'], [data-3='off'] {
  color: red
}

[data-1='on'] + [data-2='on'] + [data-3='on'] + td { // 그 옆에 있는 td를 이렇게 하겠다
  background: green
}

[data-1='off'] + [data-2='off'] + [data-3='off'] + td { // 전부 off인애를 찯아서 그 옆에 있는 td를 이렇게 하겠다
  background: red
}

@for $i from 1 through 3 {
  $ret: "";
  @for $j from 1 through 3 {
    @if $j == $i {
      $ret: $ret + '[data-' + $j + '="on"]';
    } @else {
      $ret: $ret + '[data-' + $j + '="off"]';
    }
    $ret: $ret+'+';
  }
  $ret: $ret + 'td'
  #{$ret} {
  background: yellow
}
}
```
